# Generated by Django 4.1.2 on 2022-10-30 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500, null=True)),
                ('price', models.FloatField()),
                ('weight', models.FloatField()),
                ('deliver', models.SmallIntegerField(default=7)),
                ('in_stock', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='product_photo')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category')),
            ],
        ),
    ]
